--------------------------------------------------------
--  Fichier créé - vendredi-avril-29-2016   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Sequence ACCOUNT_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "PDS"."ACCOUNT_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 21 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence CUSTOMER_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "PDS"."CUSTOMER_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 21 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence MAQ
--------------------------------------------------------

   CREATE SEQUENCE  "PDS"."MAQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 35 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence MASESQ
--------------------------------------------------------

   CREATE SEQUENCE  "PDS"."MASESQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 10 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence MASQ
--------------------------------------------------------

   CREATE SEQUENCE  "PDS"."MASQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 30 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Table ACCOUNTS
--------------------------------------------------------

  CREATE TABLE "PDS"."ACCOUNTS" 
   (	"ACCOUNT_ID" VARCHAR2(2 BYTE), 
	"CUSTOMER_ID" VARCHAR2(2 BYTE), 
	"ACCOUNT_NUM" VARCHAR2(150 BYTE), 
	"CREATION_DATE" DATE, 
	"BALANCE" NUMBER(*,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table CUSTOMERS
--------------------------------------------------------

  CREATE TABLE "PDS"."CUSTOMERS" 
   (	"CUSTOMER_ID" VARCHAR2(2 BYTE), 
	"FIRST_NAME" VARCHAR2(150 BYTE), 
	"LAST_NAME" VARCHAR2(150 BYTE), 
	"AGE" VARCHAR2(150 BYTE), 
	"SEX" VARCHAR2(150 BYTE), 
	"ACTIVITY" VARCHAR2(150 BYTE), 
	"ADRESS" VARCHAR2(150 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table EMPLOYEES
--------------------------------------------------------

  CREATE TABLE "PDS"."EMPLOYEES" 
   (	"EMPLOYEE_ID" VARCHAR2(2 BYTE), 
	"FIRST_NAME" VARCHAR2(150 BYTE), 
	"LAST_NAME" VARCHAR2(150 BYTE), 
	"LOGIN" VARCHAR2(150 BYTE), 
	"PASSWORD" VARCHAR2(150 BYTE), 
	"TYPE" VARCHAR2(20 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table INCOMECHANGEEVENTS
--------------------------------------------------------

  CREATE TABLE "PDS"."INCOMECHANGEEVENTS" 
   (	"EVENT_ID" VARCHAR2(2 BYTE), 
	"LOAN_ID" VARCHAR2(2 BYTE), 
	"DATE" DATE, 
	"NEWVALUE" FLOAT(63)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;

   COMMENT ON TABLE "PDS"."INCOMECHANGEEVENTS"  IS 'Changement des revenus';
--------------------------------------------------------
--  DDL for Table INFORMATION_TYPES
--------------------------------------------------------

  CREATE TABLE "PDS"."INFORMATION_TYPES" 
   (	"INFORMATION_TYPE_ID" VARCHAR2(2 BYTE), 
	"NAME" VARCHAR2(150 BYTE), 
	"NATURE" VARCHAR2(150 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table LOANDURATIONCHANGEEVENTS
--------------------------------------------------------

  CREATE TABLE "PDS"."LOANDURATIONCHANGEEVENTS" 
   (	"EVENT_ID" VARCHAR2(2 BYTE), 
	"LOAN_ID" VARCHAR2(2 BYTE), 
	"DATE" DATE, 
	"NEWVALUE" FLOAT(63)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table LOAN_RATE_HISTORY
--------------------------------------------------------

  CREATE TABLE "PDS"."LOAN_RATE_HISTORY" 
   (	"LRH_ID" VARCHAR2(2 BYTE), 
	"LOAN_TYPE_ID" VARCHAR2(2 BYTE), 
	"EMPLOYEE_ID" VARCHAR2(2 BYTE), 
	"VALUE" FLOAT(63), 
	"CHANGE_DATE" DATE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table LOANREDEMPTIONEVENTS
--------------------------------------------------------

  CREATE TABLE "PDS"."LOANREDEMPTIONEVENTS" 
   (	"EVENT_ID" VARCHAR2(2 BYTE), 
	"LOAN_ID" VARCHAR2(2 BYTE), 
	"STARTDATE" DATE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;

   COMMENT ON TABLE "PDS"."LOANREDEMPTIONEVENTS"  IS 'Rachat de prêt';
--------------------------------------------------------
--  DDL for Table LOANS
--------------------------------------------------------

  CREATE TABLE "PDS"."LOANS" 
   (	"LOAN_ID" VARCHAR2(2 BYTE), 
	"IS_REAL" VARCHAR2(1 BYTE), 
	"ACCOUNT_ID" VARCHAR2(2 BYTE), 
	"LOAN_TYPE_ID" VARCHAR2(2 BYTE), 
	"EFFECTIVE_DATE" DATE, 
	"CAPITAL" FLOAT(63), 
	"REMAININGOWEDCAPITAL" FLOAT(63), 
	"REPAYMENT_FREQUENCY" NUMBER(*,0), 
	"REMAINING_REPAYMENTS" NUMBER(*,0), 
	"REPAYMENT_CONSTANT" FLOAT(63), 
	"RATE_NATURE" VARCHAR2(20 BYTE), 
	"AMORTIZATION_TYPE" VARCHAR2(20 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;

   COMMENT ON COLUMN "PDS"."LOANS"."EFFECTIVE_DATE" IS 'Date de signature';
   COMMENT ON COLUMN "PDS"."LOANS"."REMAININGOWEDCAPITAL" IS 'Pincipal Restant Dû';
   COMMENT ON COLUMN "PDS"."LOANS"."REPAYMENT_CONSTANT" IS 'constant->montant de l''échéance; dégressif->montant du principal remboursé à chaque échéance. c''est la constante principale du calcul.';
--------------------------------------------------------
--  DDL for Table LOAN_TYPES
--------------------------------------------------------

  CREATE TABLE "PDS"."LOAN_TYPES" 
   (	"LOAN_TYPE_ID" VARCHAR2(2 BYTE), 
	"NAME" VARCHAR2(150 BYTE), 
	"MAX_DURATION" NUMBER(*,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;

   COMMENT ON TABLE "PDS"."LOAN_TYPES"  IS 'Types de prêts';
--------------------------------------------------------
--  DDL for Table MONTHLYCHANGE
--------------------------------------------------------

  CREATE TABLE "PDS"."MONTHLYCHANGE" 
   (	"EVENT_ID" VARCHAR2(2 BYTE), 
	"LOAN_ID" VARCHAR2(2 BYTE), 
	"DATE" DATE, 
	"NEWVALUE" FLOAT(63)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table NECESSARY_INFORMATION
--------------------------------------------------------

  CREATE TABLE "PDS"."NECESSARY_INFORMATION" 
   (	"NI_IC" VARCHAR2(2 BYTE), 
	"INFORMATION_TYPE_ID" VARCHAR2(2 BYTE), 
	"LOAN_TYPE_ID" VARCHAR2(2 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table PROVIDED_INFORMATION
--------------------------------------------------------

  CREATE TABLE "PDS"."PROVIDED_INFORMATION" 
   (	"PROVIDED_INORMATION_ID" VARCHAR2(2 BYTE), 
	"LOAN_ID" VARCHAR2(2 BYTE), 
	"INFORMATION_TYPE_ID" VARCHAR2(2 BYTE), 
	"VALUE" FLOAT(63)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table RATEMODIFICATIONEVENTS
--------------------------------------------------------

  CREATE TABLE "PDS"."RATEMODIFICATIONEVENTS" 
   (	"EVENT_ID" VARCHAR2(2 BYTE), 
	"LOAN_ID" VARCHAR2(2 BYTE), 
	"DATE" DATE, 
	"NEWVALUE" FLOAT(63)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table REPAYMENTS
--------------------------------------------------------

  CREATE TABLE "PDS"."REPAYMENTS" 
   (	"REPAYMENT_ID" VARCHAR2(2 BYTE), 
	"LOAN_ID" VARCHAR2(2 BYTE), 
	"DATE" DATE, 
	"CAPITAL" FLOAT(63), 
	"INTEREST" FLOAT(63), 
	"INSURANCE" FLOAT(63)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table TESTE
--------------------------------------------------------

  CREATE TABLE "PDS"."TESTE" 
   (	"CUSTOMER_ID" VARCHAR2(2 BYTE), 
	"FIRST_NAME" VARCHAR2(150 BYTE), 
	"LAST_NAME" VARCHAR2(150 BYTE), 
	"AGE" VARCHAR2(150 BYTE), 
	"SEX" VARCHAR2(150 BYTE), 
	"ACTIVITY" VARCHAR2(150 BYTE), 
	"ADRESS" VARCHAR2(150 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table TRANSFERTOFPAYMENTEVENTS
--------------------------------------------------------

  CREATE TABLE "PDS"."TRANSFERTOFPAYMENTEVENTS" 
   (	"EVENT_ID" VARCHAR2(2 BYTE), 
	"LOAN_ID" VARCHAR2(2 BYTE), 
	"STARTDATE" DATE, 
	"ENDDATE" DATE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table USERS
--------------------------------------------------------

  CREATE TABLE "PDS"."USERS" 
   (	"Login" VARCHAR2(150 BYTE), 
	"Password" VARCHAR2(150 BYTE), 
	"Authorization_Level" NUMBER(*,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
REM INSERTING into PDS.ACCOUNTS
SET DEFINE OFF;
REM INSERTING into PDS.CUSTOMERS
SET DEFINE OFF;
Insert into PDS.CUSTOMERS (CUSTOMER_ID,FIRST_NAME,LAST_NAME,AGE,SEX,ACTIVITY,ADRESS) values ('1','Native','trace','56','M','bondy','douala');
Insert into PDS.CUSTOMERS (CUSTOMER_ID,FIRST_NAME,LAST_NAME,AGE,SEX,ACTIVITY,ADRESS) values ('2','Ibovi','Anges','22','M','Y','Y');
REM INSERTING into PDS.EMPLOYEES
SET DEFINE OFF;
Insert into PDS.EMPLOYEES (EMPLOYEE_ID,FIRST_NAME,LAST_NAME,LOGIN,PASSWORD,TYPE) values ('1','COHEN','JOELLE','cohen','cohen','dsi');
Insert into PDS.EMPLOYEES (EMPLOYEE_ID,FIRST_NAME,LAST_NAME,LOGIN,PASSWORD,TYPE) values ('2','GIRAUD','OLIVIER','giraud','giraud','advisor');
REM INSERTING into PDS.INCOMECHANGEEVENTS
SET DEFINE OFF;
REM INSERTING into PDS.INFORMATION_TYPES
SET DEFINE OFF;
REM INSERTING into PDS.LOANDURATIONCHANGEEVENTS
SET DEFINE OFF;
REM INSERTING into PDS.LOAN_RATE_HISTORY
SET DEFINE OFF;
REM INSERTING into PDS.LOANREDEMPTIONEVENTS
SET DEFINE OFF;
REM INSERTING into PDS.LOANS
SET DEFINE OFF;
REM INSERTING into PDS.LOAN_TYPES
SET DEFINE OFF;
REM INSERTING into PDS.MONTHLYCHANGE
SET DEFINE OFF;
REM INSERTING into PDS.NECESSARY_INFORMATION
SET DEFINE OFF;
REM INSERTING into PDS.PROVIDED_INFORMATION
SET DEFINE OFF;
REM INSERTING into PDS.RATEMODIFICATIONEVENTS
SET DEFINE OFF;
REM INSERTING into PDS.REPAYMENTS
SET DEFINE OFF;
REM INSERTING into PDS.TESTE
SET DEFINE OFF;
Insert into PDS.TESTE (CUSTOMER_ID,FIRST_NAME,LAST_NAME,AGE,SEX,ACTIVITY,ADRESS) values ('3','fgfm','gfg','56','M','fg','fg');
Insert into PDS.TESTE (CUSTOMER_ID,FIRST_NAME,LAST_NAME,AGE,SEX,ACTIVITY,ADRESS) values ('4','fg','gfg','56','M','dfg','gfg');
Insert into PDS.TESTE (CUSTOMER_ID,FIRST_NAME,LAST_NAME,AGE,SEX,ACTIVITY,ADRESS) values ('7','fgml','fdfm','66','M','ffgf','fg');
REM INSERTING into PDS.TRANSFERTOFPAYMENTEVENTS
SET DEFINE OFF;
REM INSERTING into PDS.USERS
SET DEFINE OFF;
Insert into PDS.USERS ("Login","Password","Authorization_Level") values ('Boubacar','Boubacar','1');
--------------------------------------------------------
--  DDL for Index PK_NECESSARY_INFORMATION
--------------------------------------------------------

  CREATE UNIQUE INDEX "PDS"."PK_NECESSARY_INFORMATION" ON "PDS"."NECESSARY_INFORMATION" ("NI_IC") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index PK_EMPLOYEES
--------------------------------------------------------

  CREATE UNIQUE INDEX "PDS"."PK_EMPLOYEES" ON "PDS"."EMPLOYEES" ("EMPLOYEE_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index PK_LOANS
--------------------------------------------------------

  CREATE UNIQUE INDEX "PDS"."PK_LOANS" ON "PDS"."LOANS" ("LOAN_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index PK_CUSTOMERS
--------------------------------------------------------

  CREATE UNIQUE INDEX "PDS"."PK_CUSTOMERS" ON "PDS"."CUSTOMERS" ("CUSTOMER_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index PK_LOAN_RATE_HISTORY
--------------------------------------------------------

  CREATE UNIQUE INDEX "PDS"."PK_LOAN_RATE_HISTORY" ON "PDS"."LOAN_RATE_HISTORY" ("LRH_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index PK_MONTHLYCHANGE
--------------------------------------------------------

  CREATE UNIQUE INDEX "PDS"."PK_MONTHLYCHANGE" ON "PDS"."MONTHLYCHANGE" ("EVENT_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index PK_TRANSFERTOFPAYMENTEVENTS
--------------------------------------------------------

  CREATE UNIQUE INDEX "PDS"."PK_TRANSFERTOFPAYMENTEVENTS" ON "PDS"."TRANSFERTOFPAYMENTEVENTS" ("EVENT_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index PK_INCOMECHANGEEVENTS
--------------------------------------------------------

  CREATE UNIQUE INDEX "PDS"."PK_INCOMECHANGEEVENTS" ON "PDS"."INCOMECHANGEEVENTS" ("EVENT_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index PK_LOANDURATIONCHANGEEVENTS
--------------------------------------------------------

  CREATE UNIQUE INDEX "PDS"."PK_LOANDURATIONCHANGEEVENTS" ON "PDS"."LOANDURATIONCHANGEEVENTS" ("EVENT_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index PK_REPAYMENTS
--------------------------------------------------------

  CREATE UNIQUE INDEX "PDS"."PK_REPAYMENTS" ON "PDS"."REPAYMENTS" ("REPAYMENT_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index PK_PROVIDED_INFORMATION
--------------------------------------------------------

  CREATE UNIQUE INDEX "PDS"."PK_PROVIDED_INFORMATION" ON "PDS"."PROVIDED_INFORMATION" ("PROVIDED_INORMATION_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index PK_RATEMODIFICATIONEVENTS
--------------------------------------------------------

  CREATE UNIQUE INDEX "PDS"."PK_RATEMODIFICATIONEVENTS" ON "PDS"."RATEMODIFICATIONEVENTS" ("EVENT_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index PK_LOAN_TYPES
--------------------------------------------------------

  CREATE UNIQUE INDEX "PDS"."PK_LOAN_TYPES" ON "PDS"."LOAN_TYPES" ("LOAN_TYPE_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index USERS_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "PDS"."USERS_PK" ON "PDS"."USERS" ("Login") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index PK_ACCOUNTS
--------------------------------------------------------

  CREATE UNIQUE INDEX "PDS"."PK_ACCOUNTS" ON "PDS"."ACCOUNTS" ("ACCOUNT_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index PK_LOANREDEMPTIONEVENTS
--------------------------------------------------------

  CREATE UNIQUE INDEX "PDS"."PK_LOANREDEMPTIONEVENTS" ON "PDS"."LOANREDEMPTIONEVENTS" ("EVENT_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index PK_INFORMATION_TYPES
--------------------------------------------------------

  CREATE UNIQUE INDEX "PDS"."PK_INFORMATION_TYPES" ON "PDS"."INFORMATION_TYPES" ("INFORMATION_TYPE_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  Constraints for Table INCOMECHANGEEVENTS
--------------------------------------------------------

  ALTER TABLE "PDS"."INCOMECHANGEEVENTS" MODIFY ("EVENT_ID" NOT NULL ENABLE);
  ALTER TABLE "PDS"."INCOMECHANGEEVENTS" MODIFY ("DATE" NOT NULL ENABLE);
  ALTER TABLE "PDS"."INCOMECHANGEEVENTS" MODIFY ("NEWVALUE" NOT NULL ENABLE);
  ALTER TABLE "PDS"."INCOMECHANGEEVENTS" ADD CONSTRAINT "PK_INCOMECHANGEEVENTS" PRIMARY KEY ("EVENT_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
--------------------------------------------------------
--  Constraints for Table USERS
--------------------------------------------------------

  ALTER TABLE "PDS"."USERS" ADD CONSTRAINT "USERS_PK" PRIMARY KEY ("Login")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
--------------------------------------------------------
--  Constraints for Table CUSTOMERS
--------------------------------------------------------

  ALTER TABLE "PDS"."CUSTOMERS" MODIFY ("CUSTOMER_ID" NOT NULL ENABLE);
  ALTER TABLE "PDS"."CUSTOMERS" ADD CONSTRAINT "PK_CUSTOMERS" PRIMARY KEY ("CUSTOMER_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
--------------------------------------------------------
--  Constraints for Table TESTE
--------------------------------------------------------

  ALTER TABLE "PDS"."TESTE" MODIFY ("CUSTOMER_ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table LOAN_TYPES
--------------------------------------------------------

  ALTER TABLE "PDS"."LOAN_TYPES" MODIFY ("LOAN_TYPE_ID" NOT NULL ENABLE);
  ALTER TABLE "PDS"."LOAN_TYPES" MODIFY ("NAME" NOT NULL ENABLE);
  ALTER TABLE "PDS"."LOAN_TYPES" ADD CONSTRAINT "PK_LOAN_TYPES" PRIMARY KEY ("LOAN_TYPE_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
--------------------------------------------------------
--  Constraints for Table PROVIDED_INFORMATION
--------------------------------------------------------

  ALTER TABLE "PDS"."PROVIDED_INFORMATION" MODIFY ("PROVIDED_INORMATION_ID" NOT NULL ENABLE);
  ALTER TABLE "PDS"."PROVIDED_INFORMATION" MODIFY ("VALUE" NOT NULL ENABLE);
  ALTER TABLE "PDS"."PROVIDED_INFORMATION" ADD CONSTRAINT "PK_PROVIDED_INFORMATION" PRIMARY KEY ("PROVIDED_INORMATION_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
--------------------------------------------------------
--  Constraints for Table RATEMODIFICATIONEVENTS
--------------------------------------------------------

  ALTER TABLE "PDS"."RATEMODIFICATIONEVENTS" MODIFY ("EVENT_ID" NOT NULL ENABLE);
  ALTER TABLE "PDS"."RATEMODIFICATIONEVENTS" MODIFY ("DATE" NOT NULL ENABLE);
  ALTER TABLE "PDS"."RATEMODIFICATIONEVENTS" MODIFY ("NEWVALUE" NOT NULL ENABLE);
  ALTER TABLE "PDS"."RATEMODIFICATIONEVENTS" ADD CONSTRAINT "PK_RATEMODIFICATIONEVENTS" PRIMARY KEY ("EVENT_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
--------------------------------------------------------
--  Constraints for Table EMPLOYEES
--------------------------------------------------------

  ALTER TABLE "PDS"."EMPLOYEES" MODIFY ("EMPLOYEE_ID" NOT NULL ENABLE);
  ALTER TABLE "PDS"."EMPLOYEES" MODIFY ("FIRST_NAME" NOT NULL ENABLE);
  ALTER TABLE "PDS"."EMPLOYEES" MODIFY ("LOGIN" NOT NULL ENABLE);
  ALTER TABLE "PDS"."EMPLOYEES" MODIFY ("PASSWORD" NOT NULL ENABLE);
  ALTER TABLE "PDS"."EMPLOYEES" ADD CONSTRAINT "PK_EMPLOYEES" PRIMARY KEY ("EMPLOYEE_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "PDS"."EMPLOYEES" MODIFY ("TYPE" NOT NULL ENABLE);
  ALTER TABLE "PDS"."EMPLOYEES" ADD CHECK (type in ('advisor','dsi','director')) ENABLE;
--------------------------------------------------------
--  Constraints for Table LOANREDEMPTIONEVENTS
--------------------------------------------------------

  ALTER TABLE "PDS"."LOANREDEMPTIONEVENTS" MODIFY ("EVENT_ID" NOT NULL ENABLE);
  ALTER TABLE "PDS"."LOANREDEMPTIONEVENTS" MODIFY ("STARTDATE" NOT NULL ENABLE);
  ALTER TABLE "PDS"."LOANREDEMPTIONEVENTS" ADD CONSTRAINT "PK_LOANREDEMPTIONEVENTS" PRIMARY KEY ("EVENT_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
--------------------------------------------------------
--  Constraints for Table MONTHLYCHANGE
--------------------------------------------------------

  ALTER TABLE "PDS"."MONTHLYCHANGE" MODIFY ("EVENT_ID" NOT NULL ENABLE);
  ALTER TABLE "PDS"."MONTHLYCHANGE" MODIFY ("DATE" NOT NULL ENABLE);
  ALTER TABLE "PDS"."MONTHLYCHANGE" MODIFY ("NEWVALUE" NOT NULL ENABLE);
  ALTER TABLE "PDS"."MONTHLYCHANGE" ADD CONSTRAINT "PK_MONTHLYCHANGE" PRIMARY KEY ("EVENT_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
--------------------------------------------------------
--  Constraints for Table TRANSFERTOFPAYMENTEVENTS
--------------------------------------------------------

  ALTER TABLE "PDS"."TRANSFERTOFPAYMENTEVENTS" MODIFY ("EVENT_ID" NOT NULL ENABLE);
  ALTER TABLE "PDS"."TRANSFERTOFPAYMENTEVENTS" MODIFY ("STARTDATE" NOT NULL ENABLE);
  ALTER TABLE "PDS"."TRANSFERTOFPAYMENTEVENTS" MODIFY ("ENDDATE" NOT NULL ENABLE);
  ALTER TABLE "PDS"."TRANSFERTOFPAYMENTEVENTS" ADD CONSTRAINT "PK_TRANSFERTOFPAYMENTEVENTS" PRIMARY KEY ("EVENT_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
--------------------------------------------------------
--  Constraints for Table NECESSARY_INFORMATION
--------------------------------------------------------

  ALTER TABLE "PDS"."NECESSARY_INFORMATION" MODIFY ("NI_IC" NOT NULL ENABLE);
  ALTER TABLE "PDS"."NECESSARY_INFORMATION" ADD CONSTRAINT "PK_NECESSARY_INFORMATION" PRIMARY KEY ("NI_IC")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
--------------------------------------------------------
--  Constraints for Table LOANDURATIONCHANGEEVENTS
--------------------------------------------------------

  ALTER TABLE "PDS"."LOANDURATIONCHANGEEVENTS" MODIFY ("EVENT_ID" NOT NULL ENABLE);
  ALTER TABLE "PDS"."LOANDURATIONCHANGEEVENTS" MODIFY ("DATE" NOT NULL ENABLE);
  ALTER TABLE "PDS"."LOANDURATIONCHANGEEVENTS" MODIFY ("NEWVALUE" NOT NULL ENABLE);
  ALTER TABLE "PDS"."LOANDURATIONCHANGEEVENTS" ADD CONSTRAINT "PK_LOANDURATIONCHANGEEVENTS" PRIMARY KEY ("EVENT_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
--------------------------------------------------------
--  Constraints for Table REPAYMENTS
--------------------------------------------------------

  ALTER TABLE "PDS"."REPAYMENTS" MODIFY ("REPAYMENT_ID" NOT NULL ENABLE);
  ALTER TABLE "PDS"."REPAYMENTS" MODIFY ("DATE" NOT NULL ENABLE);
  ALTER TABLE "PDS"."REPAYMENTS" MODIFY ("CAPITAL" NOT NULL ENABLE);
  ALTER TABLE "PDS"."REPAYMENTS" MODIFY ("INTEREST" NOT NULL ENABLE);
  ALTER TABLE "PDS"."REPAYMENTS" MODIFY ("INSURANCE" NOT NULL ENABLE);
  ALTER TABLE "PDS"."REPAYMENTS" ADD CONSTRAINT "PK_REPAYMENTS" PRIMARY KEY ("REPAYMENT_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
--------------------------------------------------------
--  Constraints for Table ACCOUNTS
--------------------------------------------------------

  ALTER TABLE "PDS"."ACCOUNTS" MODIFY ("ACCOUNT_ID" NOT NULL ENABLE);
  ALTER TABLE "PDS"."ACCOUNTS" MODIFY ("ACCOUNT_NUM" NOT NULL ENABLE);
  ALTER TABLE "PDS"."ACCOUNTS" MODIFY ("CREATION_DATE" NOT NULL ENABLE);
  ALTER TABLE "PDS"."ACCOUNTS" ADD CONSTRAINT "PK_ACCOUNTS" PRIMARY KEY ("ACCOUNT_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
--------------------------------------------------------
--  Constraints for Table LOANS
--------------------------------------------------------

  ALTER TABLE "PDS"."LOANS" MODIFY ("LOAN_ID" NOT NULL ENABLE);
  ALTER TABLE "PDS"."LOANS" MODIFY ("RATE_NATURE" NOT NULL ENABLE);
  ALTER TABLE "PDS"."LOANS" MODIFY ("EFFECTIVE_DATE" NOT NULL ENABLE);
  ALTER TABLE "PDS"."LOANS" MODIFY ("AMORTIZATION_TYPE" NOT NULL ENABLE);
  ALTER TABLE "PDS"."LOANS" ADD CHECK (Rate_Nature in ('fixe rate','floating rate')) ENABLE;
  ALTER TABLE "PDS"."LOANS" ADD CONSTRAINT "PK_LOANS" PRIMARY KEY ("LOAN_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "PDS"."LOANS" ADD CHECK (Amortization_Type in ('steady','degressive')) ENABLE;
--------------------------------------------------------
--  Constraints for Table INFORMATION_TYPES
--------------------------------------------------------

  ALTER TABLE "PDS"."INFORMATION_TYPES" MODIFY ("INFORMATION_TYPE_ID" NOT NULL ENABLE);
  ALTER TABLE "PDS"."INFORMATION_TYPES" ADD CONSTRAINT "PK_INFORMATION_TYPES" PRIMARY KEY ("INFORMATION_TYPE_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
--------------------------------------------------------
--  Constraints for Table LOAN_RATE_HISTORY
--------------------------------------------------------

  ALTER TABLE "PDS"."LOAN_RATE_HISTORY" MODIFY ("LRH_ID" NOT NULL ENABLE);
  ALTER TABLE "PDS"."LOAN_RATE_HISTORY" MODIFY ("VALUE" NOT NULL ENABLE);
  ALTER TABLE "PDS"."LOAN_RATE_HISTORY" MODIFY ("CHANGE_DATE" NOT NULL ENABLE);
  ALTER TABLE "PDS"."LOAN_RATE_HISTORY" ADD CONSTRAINT "PK_LOAN_RATE_HISTORY" PRIMARY KEY ("LRH_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table ACCOUNTS
--------------------------------------------------------

  ALTER TABLE "PDS"."ACCOUNTS" ADD CONSTRAINT "FK_ACCOUNTS_REFERENCE_CUSTOMER" FOREIGN KEY ("CUSTOMER_ID")
	  REFERENCES "PDS"."CUSTOMERS" ("CUSTOMER_ID") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table INCOMECHANGEEVENTS
--------------------------------------------------------

  ALTER TABLE "PDS"."INCOMECHANGEEVENTS" ADD CONSTRAINT "FK_INCOMECH_REFERENCE_LOANS" FOREIGN KEY ("LOAN_ID")
	  REFERENCES "PDS"."LOANS" ("LOAN_ID") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table LOANDURATIONCHANGEEVENTS
--------------------------------------------------------

  ALTER TABLE "PDS"."LOANDURATIONCHANGEEVENTS" ADD CONSTRAINT "FK_LOANDURA_REFERENCE_LOANS" FOREIGN KEY ("LOAN_ID")
	  REFERENCES "PDS"."LOANS" ("LOAN_ID") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table LOAN_RATE_HISTORY
--------------------------------------------------------

  ALTER TABLE "PDS"."LOAN_RATE_HISTORY" ADD CONSTRAINT "FK_LOAN_RAT_REFERENCE_EMPLOYEE" FOREIGN KEY ("EMPLOYEE_ID")
	  REFERENCES "PDS"."EMPLOYEES" ("EMPLOYEE_ID") ENABLE;
  ALTER TABLE "PDS"."LOAN_RATE_HISTORY" ADD CONSTRAINT "FK_LOAN_RAT_REFERENCE_LOAN_TYP" FOREIGN KEY ("LOAN_TYPE_ID")
	  REFERENCES "PDS"."LOAN_TYPES" ("LOAN_TYPE_ID") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table LOANREDEMPTIONEVENTS
--------------------------------------------------------

  ALTER TABLE "PDS"."LOANREDEMPTIONEVENTS" ADD CONSTRAINT "FK_LOANREDE_REFERENCE_LOANS" FOREIGN KEY ("LOAN_ID")
	  REFERENCES "PDS"."LOANS" ("LOAN_ID") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table LOANS
--------------------------------------------------------

  ALTER TABLE "PDS"."LOANS" ADD CONSTRAINT "FK_LOANS_REFERENCE_ACCOUNTS" FOREIGN KEY ("ACCOUNT_ID")
	  REFERENCES "PDS"."ACCOUNTS" ("ACCOUNT_ID") ENABLE;
  ALTER TABLE "PDS"."LOANS" ADD CONSTRAINT "FK_LOANS_REFERENCE_LOAN_TYP" FOREIGN KEY ("LOAN_TYPE_ID")
	  REFERENCES "PDS"."LOAN_TYPES" ("LOAN_TYPE_ID") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table MONTHLYCHANGE
--------------------------------------------------------

  ALTER TABLE "PDS"."MONTHLYCHANGE" ADD CONSTRAINT "FK_MONTHLYC_REFERENCE_LOANS" FOREIGN KEY ("LOAN_ID")
	  REFERENCES "PDS"."LOANS" ("LOAN_ID") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table NECESSARY_INFORMATION
--------------------------------------------------------

  ALTER TABLE "PDS"."NECESSARY_INFORMATION" ADD CONSTRAINT "FK_NECESSAR_REFERENCE_INFORMAT" FOREIGN KEY ("INFORMATION_TYPE_ID")
	  REFERENCES "PDS"."INFORMATION_TYPES" ("INFORMATION_TYPE_ID") ENABLE;
  ALTER TABLE "PDS"."NECESSARY_INFORMATION" ADD CONSTRAINT "FK_NECESSAR_REFERENCE_LOAN_TYP" FOREIGN KEY ("LOAN_TYPE_ID")
	  REFERENCES "PDS"."LOAN_TYPES" ("LOAN_TYPE_ID") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table PROVIDED_INFORMATION
--------------------------------------------------------

  ALTER TABLE "PDS"."PROVIDED_INFORMATION" ADD CONSTRAINT "FK_PROVIDED_REFERENCE_INFORMAT" FOREIGN KEY ("INFORMATION_TYPE_ID")
	  REFERENCES "PDS"."INFORMATION_TYPES" ("INFORMATION_TYPE_ID") ENABLE;
  ALTER TABLE "PDS"."PROVIDED_INFORMATION" ADD CONSTRAINT "FK_PROVIDED_REFERENCE_LOANS" FOREIGN KEY ("LOAN_ID")
	  REFERENCES "PDS"."LOANS" ("LOAN_ID") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table RATEMODIFICATIONEVENTS
--------------------------------------------------------

  ALTER TABLE "PDS"."RATEMODIFICATIONEVENTS" ADD CONSTRAINT "FK_RATEMODI_REFERENCE_LOANS" FOREIGN KEY ("LOAN_ID")
	  REFERENCES "PDS"."LOANS" ("LOAN_ID") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table REPAYMENTS
--------------------------------------------------------

  ALTER TABLE "PDS"."REPAYMENTS" ADD CONSTRAINT "FK_REPAYMEN_REFERENCE_LOANS" FOREIGN KEY ("LOAN_ID")
	  REFERENCES "PDS"."LOANS" ("LOAN_ID") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table TRANSFERTOFPAYMENTEVENTS
--------------------------------------------------------

  ALTER TABLE "PDS"."TRANSFERTOFPAYMENTEVENTS" ADD CONSTRAINT "FK_TRANSFER_REFERENCE_LOANS" FOREIGN KEY ("LOAN_ID")
	  REFERENCES "PDS"."LOANS" ("LOAN_ID") ENABLE;
